---
- hosts: all
  gather_facts: False

  tasks:
  - name: Backup Configuration
    ios_config:
      backup: yes
      provider: '{{ cli }}'
      backup_options:
        dir_path: /configurations/backup_configurations
...