
---
- hosts: all
  gather_facts: False

  tasks:
  - name: Create directory
    file:
      path: /configurations/ios/configuration_backups/_routers
      state: directory
    delegate_to: localhost
    run_once: true

  - name: Backup Running Configuration
    ios_command:
      commands: show running-config
    register: running_config

  - name: Save Running Configuration to a File
    copy:
      content: '{{ running_config.stdout[0] }}'
      dest: /configurations/ios/configuration_backups/_routers/{{ inventory_hostname }}.config
...