
---
- hosts: all
  gather_facts: False

  tasks:
  - name: Default interface
    ios_l2_interface:
      name: '{{ item.name }}'
      state: unconfigured
    with_items: '{{ interfaces }}'

  - name: Update interface description and shutdown
    ios_config:
      lines:
        - description {{ item.description }}
        - shutdown
      parents: interface {{ item.name }}
    with_items: '{{ interfaces }}'
  
  - name: Save running configuration when modified
    ios_config:
      save_when: modified
...