---
- name: Rocklin MPLS Router | Check route table for store POS subnet
  ansible.builtin.command: >
    {{ playbook_dir }}/library/go/ios-cli device run commands
      --insecure
      --timeout 60
      --command "show ip route | include {{ store_subnet }}"
      {{ rocklin_mpls_router }}
  register: store_subnet_lookup
  changed_when: false
  ignore_errors: true

- name: Rocklin MPLS Router | Fetch store broadband VPN tunnel status
  ansible.builtin.command: >
    {{ playbook_dir }}/library/go/ios-cli device run commands
      --insecure
      --timeout 60
      --command "show ip bgp neighbors {{ store_bb_tun1 }} routes | include ^Total .+[1-9][0-9]* *$"
      {{ rocklin_mpls_router }}
  register: store_bb_tunnel_status
  changed_when: false
  when: not sdwan_store
  ignore_errors: true

- name: Rocklin MPLS Router | Fetch store broadband VPN tunnel down count
  ansible.builtin.command: >
    {{ playbook_dir }}/library/go/ios-cli device run commands
      --insecure
      --timeout 60
      --command "show ip bgp summary | count [^0-9]$"
      {{ rocklin_mpls_router }}
  register: store_vpn_down_count
  changed_when: false
  when: not sdwan_store
  ignore_errors: true

- name: Rocklin MPLS Router | Ping store router
  ansible.builtin.command: >
    {{ playbook_dir }}/library/go/ios-cli device run commands
      --insecure
      --timeout 60
      --command "ping {{ store_router }}"
      {{ rocklin_mpls_router }}
  register: store_router_ping
  changed_when: false
  ignore_errors: true

- name: Rocklin MPLS Router | Ping store switch
  ansible.builtin.command: >
    {{ playbook_dir }}/library/go/ios-cli device run commands
      --insecure
      --timeout 60
      --command "ping {{ store_switch }}"
      {{ rocklin_mpls_router }}
  register: store_switch_ping
  changed_when: false
  ignore_errors: true
