---
- hosts: all
  gather_facts: false

  tasks:
    - name: Execute Operational Command
      ios_command:
        commands: "{{ command }}"
      register: result

    - debug:
        var: result.stdout_lines[0]
