---
- hosts: all
  gather_facts: false

  tasks:
    - name: Execute Operational Command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: result

    - ansible.builtin.debug:
        var: result.stdout_lines[0]
