---
- hosts: "{{ hosts_limit | lower }}"
  gather_facts: false

  tasks:
    - name: No shutdown interface
      cisco.ios.ios_config:
        lines:
          - no shutdown
        parents: interface {{ item }}
      with_items: "{{ interfaces }}"

    - name: Save running configuration when modified
      cisco.ios.ios_config:
        save_when: modified
