---
- hosts: all
  gather_facts: false

  tasks:
    - name: Shutdown interface
      cisco.ios.ios_config:
        lines:
          - shutdown
        parents: interface {{ item }}
      with_items: "{{ interfaces }}"

    - name: Save running configuration when modified
      cisco.ios.ios_config:
        save_when: modified
