---
- name: Validate Partner Connections
  hosts: localhost
  gather_facts: false
  roles:
    - role: Output

  tasks:
    block:
      - name: Create panos-cli configuration file
        ansible.builtin.copy:
          dest: /home/runner/.panos-cli.yml
          content: |
            apikey: "{{ panw_api_token }}"
            user: "{{ panw_user }}"
            password: "{{ panw_password }}"
        no_log: true
        when: "'/home/runner/.panos-cli.yml' is not file"

      - name: Fetch Ashburn active partner connections
        ansible.builtin.shell: "{{ playbook_dir }}/library/go/panos-cli firewall run commands --no-config --insecure --expect-timeout 60 --user {{ panos_user }} --password {{ panos_ssh_pass }} --command 'show session all filter state active destination {{ partner.ip }} count yes' {{ firewalls.asbc1_corp_edge }} | egrep '\\*{3} show|ACTIVE'"
        register: active_partner_sessions_ashburn_job
        changed_when: false
        delegate_to: localhost
        loop: "{{ partner_connections }}"
        loop_control:
          loop_var: partner
        async: 60
        poll: 0

      - name: Fetch Rocklin active partner connections
        ansible.builtin.shell: "{{ playbook_dir }}/library/go/panos-cli firewall run commands --no-config --insecure --expect-timeout 60 --user {{ panos_user }} --password {{ panos_ssh_pass }} --command 'show session all filter state active destination {{ partner.ip }} count yes' {{ firewalls.rkat1_corp_edge }} | egrep '\\*{3} show|ACTIVE'"
        register: active_partner_sessions_rocklin_job
        changed_when: false
        delegate_to: localhost
        loop: "{{ partner_connections }}"
        loop_control:
          loop_var: partner
        async: 60
        poll: 0

      - name: Fetch Sacramento active partner connections
        ansible.builtin.shell: "{{ playbook_dir }}/library/go/panos-cli firewall run commands --no-config --insecure --expect-timeout 60 --user {{ panos_user }} --password {{ panos_ssh_pass }} --command 'show session all filter state active destination {{ partner.ip }} count yes' {{ firewalls.sast1_corp_edge }} | egrep '\\*{3} show|ACTIVE'"
        register: active_partner_sessions_sacramento_job
        changed_when: false
        delegate_to: localhost
        loop: "{{ partner_connections }}"
        loop_control:
          loop_var: partner
        async: 60
        poll: 0

      - name: Wait for async jobs to finish
        ansible.builtin.async_status:
          jid: "{{ job.ansible_job_id }}"
        register: jobs
        until: jobs.finished
        retries: 60
        delay: 1
        loop: "{{ [active_partner_sessions_ashburn_job, active_partner_sessions_rocklin_job, active_partner_sessions_sacramento_job] }}"
        loop_control:
          loop_var: job

      - name: Set parnter session facts
        ansible.builtin.set_fact:
          active_partner_sessions_ashburn: "{{ jobs.results[0] }}"
          active_partner_sessions_rocklin: "{{ jobs.results[1] }}"
          active_partner_sessions_sacramento: "{{ jobs.results[2] }}"
    ignore_errors: true


##### External Partner Services ##############################

{% for item in results.results %}
{{ item.service.name }} {{ item.service.fqdn }} ({{ item.service.ip }}) active firewall sessions:
{{ item.stdout_lines[0] | regex_replace("[^\x20-\x7e]", "") | regex_replace("\s?\*{3}\s?", "") }}: {{ item.stdout_lines[1] | regex_replace("[^\x20-\x7e]", "") | regex_replace("[^0-9]", "") }}
{{ item.stdout_lines[2] | regex_replace("[^\x20-\x7e]", "") | regex_replace("\s?\*{3}\s?", "") }}: {{ item.stdout_lines[3] | regex_replace("[^\x20-\x7e]", "") | regex_replace("[^0-9]", "") }}
{{ item.stdout_lines[4] | regex_replace("[^\x20-\x7e]", "") | regex_replace("\s?\*{3}\s?", "") }}: {{ item.stdout_lines[5] | regex_replace("[^\x20-\x7e]", "") | regex_replace("[^0-9]", "") }}

{% endfor %}
