---
- hosts: "{{ hosts_limit | lower }}"
  gather_facts: false

  tasks:
    - name: Run exec command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: result

    - ansible.builtin.debug:
        var: result.stdout_lines[0]
