---
- hosts: switches
  gather_facts: false

  tasks:
    - name: Run exec command
      cisco.ios.ios_command:
        commands: "{{ command }}"
      register: result

    - debug:
        var: result.stdout_lines[0]
